---
title: "Warmup Activity"
format: html
editor: visual

execute: 
  warning: false
---

------------------------------------------------------------------------

## Warm-up Activity

```{r}
animals <- c("brown bear", "red bird", "yellow duck", "blue horse")

# for (i in seq(from = 1, to = 3)){
  for (i in 1:(length(animals)-1)) {
print(paste0(animals[i], ", ", animals[i], ", what do you see? I see a ", animals[i+1], " looking at me."))
}
```

------------------------------------------------------------------------

## Interactive Session Pt1

```{r}
library(tidyverse)
library(here)
library(janitor)

```

```{r}
wb_indicators<- read_csv(here("data", "wb_indicators.csv"), na = c("", "..")) %>% 
  pivot_longer(cols = "2001 [YR2001]":"2020 [YR2020]", 
               names_to = "year", 
               values_to = "indicator value") %>%
  separate("year", into = c("year", "year_chr"), sep = " ") %>% 
  dplyr::select(-year_chr, -"Country Code", -"Series Code") 

wb_indicators_tidy <- wb_indicators %>% 
  tidyr::drop_na("Series Name") %>% 
  pivot_wider(names_from = "Series Name", values_from = "indicator value") 


# view(wb_indicators_tidy)
```

```{r}
# names(wb_indicators_tidy) <- c("country",
#                                "year",
#                                "access_clean_fuels_pp",
#                                "access_electricity_pp",
#                                "co2_emissions_kt",
#                                "fossil_fuels_cons_pt",
#                                "water_stress")
```

```{r}
wb_ind <- wb_indicators_tidy %>% 
  dplyr::rename(country = "Country Name",
                access_clean_fuel_pp = "Access to clean fuels and technologies for cooking (% of population)",
                access_electricity_pp = "Access to electricity (% of population)",
                co2_emissions_kt = "CO2 emissions (kt)",
                fossil_fuels_cons_pt = "Fossil fuel energy consumption (% of total)",
                water_stress = "Level of water stress: freshwater withdrawal as a proportion of available freshwater resources") %>% 
  dplyr::mutate(year = as.numeric(year))
```

```{r}
ggplot(data = wb_ind, aes(x = year, y = co2_emissions_kt))+
  geom_line(aes(color = country))+
  theme(legend.position = "none")
```
